In [17]:
import numpy as np
import matplotlib.pyplot as plt

# Exercise 7-1
- convert a covariance matrix into a correlation matrix
- involves dividing each matrix element (i.e. each covariance between each pair of variables) by the product of the variance of those two variables
- Done by pre- and postmulitplying the covariance matrix by a diagonal matrix containing inverted standard deviations of each variable (std dev is sqrt(var)).
- The standard deviation is inverted because we need to divide by the variances although we will multiply the matrices
- We can do this because of a special property of pre and post multiplying diagonal matrices (exercise 5-11)

$$
R = SCS
$$

In [27]:
data_points = 5
data = np.random.default_rng().random((data_points, data_points))
data

array([[0.04515274, 0.62152931, 0.95055193, 0.15953407, 0.78428725],
       [0.17731897, 0.26864754, 0.0843931 , 0.04131006, 0.8231935 ],
       [0.59134812, 0.41590843, 0.28450387, 0.40705198, 0.6323555 ],
       [0.19998631, 0.54977848, 0.86938013, 0.67969458, 0.92927522],
       [0.90810413, 0.52658318, 0.15612451, 0.77895662, 0.06210594]])

In [28]:
# mean center the data
data_mean_centered = data - np.mean(data, axis=0)
# find the covariance by premultiplying the transpose and normalizing by the count
data_cov = data_mean_centered.T @ data_mean_centered
data_cov /= (data_mean_centered.shape[0] - 1)
data_cov

array([[ 0.1272683 , -0.00149565, -0.08989782,  0.07604938, -0.11111456],
       [-0.00149565,  0.01894639,  0.04365725,  0.01968208, -0.00610823],
       [-0.08989782,  0.04365725,  0.16801222,  0.00356882,  0.07426598],
       [ 0.07604938,  0.01968208,  0.00356882,  0.10187088, -0.05974082],
       [-0.11111456, -0.00610823,  0.07426598, -0.05974082,  0.11797097]])

In [29]:
# std dev is the square root of the variance
std_dev = np.sqrt(np.diag(data_cov))
# we need the inverse square root
S = np.diag(1/std_dev)

In [30]:
# do the pre and post multiply
obs_corr = S @ data_cov @ S
obs_corr
# observe the diagonals of being 1 which makes sense. A variable is correlated with itself

array([[ 1.        , -0.03045834, -0.61477839,  0.66789856, -0.90682451],
       [-0.03045834,  1.        ,  0.77378932,  0.44800501, -0.12920073],
       [-0.61477839,  0.77378932,  1.        ,  0.02727902,  0.52751147],
       [ 0.66789856,  0.44800501,  0.02727902,  1.        , -0.54495242],
       [-0.90682451, -0.12920073,  0.52751147, -0.54495242,  1.        ]])

# Exercise 7-2
- Use the numpy built in to see if there is a difference

In [33]:
numpy_corr = np.corrcoef(data)
numpy_corr

array([[ 1.        ,  0.38677761, -0.34300721,  0.78626714, -0.94800345],
       [ 0.38677761,  1.        ,  0.70256731,  0.40393023, -0.59286013],
       [-0.34300721,  0.70256731,  1.        , -0.27812743,  0.10751241],
       [ 0.78626714,  0.40393023, -0.27812743,  1.        , -0.86706568],
       [-0.94800345, -0.59286013,  0.10751241, -0.86706568,  1.        ]])

In [36]:
obs_corr - numpy_corr
# observe a very small different that can be attributed to rounding errors

array([[ 0.00000000e+00, -4.17235953e-01, -2.71771178e-01,
        -1.18368584e-01,  4.11789458e-02],
       [-4.17235953e-01,  2.22044605e-16,  7.12220087e-02,
         4.40747832e-02,  4.63659399e-01],
       [-2.71771178e-01,  7.12220087e-02, -1.11022302e-16,
         3.05406453e-01,  4.19999070e-01],
       [-1.18368584e-01,  4.40747832e-02,  3.05406453e-01,
         0.00000000e+00,  3.22113257e-01],
       [ 4.11789458e-02,  4.63659399e-01,  4.19999070e-01,
         3.22113257e-01, -2.22044605e-16]])