In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Exercise 8-1
- Illustrate using python that $(A^{-1})^{-1} = A$

In [12]:
A = np.trunc(np.random.default_rng().random((4, 4)) * 10 **3) / 10**3
A

array([[0.482, 0.187, 0.447, 0.178],
       [0.631, 0.427, 0.755, 0.23 ],
       [0.761, 0.855, 0.128, 0.823],
       [0.896, 0.465, 0.049, 0.952]])

In [18]:
# While not exact due to rounding errors this shows that the inverse of the inverse is the original matrix
np.trunc(np.linalg.inv(np.linalg.inv(A)) * 10 ** 3) / 10**3 - A

array([[-0.001,  0.   , -0.001,  0.   ],
       [ 0.   ,  0.   , -0.001,  0.   ],
       [-0.001, -0.001, -0.001, -0.001],
       [-0.001, -0.001, -0.001, -0.001]])

# Exercise 8-2
- Implement full "inverting any square full-rank matrix" algo

In [30]:
A = np.random.default_rng().random((4, 4))
A

array([[0.88470284, 0.34774797, 0.20997003, 0.05637225],
       [0.05716204, 0.95304091, 0.20831214, 0.66490392],
       [0.34090445, 0.85992446, 0.02686301, 0.51418276],
       [0.55347299, 0.35540732, 0.45486333, 0.63240455]])

In [55]:
row_count = A.shape[0]
col_count = A.shape[1]

minors_matrix = np.zeros((row_count, col_count))

for row_idx in range(row_count):
    for col_idx in range(col_count):
        row_mask = np.arange(A.shape[0]) != row_idx
        col_mask = np.arange(A.shape[1]) != col_idx
        sum_matrix = A[row_mask][:, col_mask]
        minors_matrix[row_idx][col_idx] = np.linalg.det(sum_matrix)
minors_matrix

array([[-0.02819804,  0.09519224, -0.1495014 , -0.18570641],
       [-0.12972806, -0.16949679,  0.32343825,  0.21435586],
       [-0.11602968, -0.08637503,  0.41096372,  0.24258419],
       [ 0.03954217,  0.11646458, -0.01924818, -0.16956559]])

In [61]:
grid_matrix = np.zeros((row_count, col_count))
for row_idx in range(row_count):
    for col_idx in range(col_count):
        grid_matrix[row_idx][col_idx] = (-1)**(row_idx +col_idx + 2)
grid_matrix

array([[ 1., -1.,  1., -1.],
       [-1.,  1., -1.,  1.],
       [ 1., -1.,  1., -1.],
       [-1.,  1., -1.,  1.]])

In [62]:
cofactors_matrix = minors_matrix * grid_matrix
cofactors_matrix

array([[-0.02819804, -0.09519224, -0.1495014 ,  0.18570641],
       [ 0.12972806, -0.16949679, -0.32343825,  0.21435586],
       [-0.11602968,  0.08637503,  0.41096372, -0.24258419],
       [-0.03954217,  0.11646458,  0.01924818, -0.16956559]])

In [70]:
adjunct_matrix = cofactors_matrix.T * np.linalg.det(A)**(-1)
adjunct_matrix

array([[ 0.35706409, -1.64271126,  1.46925243,  0.50071174],
       [ 1.20539361,  2.14629195, -1.09374366, -1.47475939],
       [ 1.89309576,  4.09561096, -5.20392223, -0.24373444],
       [-2.35154994, -2.71433024,  3.07177794,  2.14716312]])

In [72]:
# Given the adjunct matrix is the inverse of A this should roughly be the identity matrix. It is but with rounding errors
adjunct_matrix @ A

array([[ 1.00000000e+00,  2.22044605e-16,  1.24900090e-16,
         1.11022302e-16],
       [ 5.55111512e-16,  1.00000000e+00,  1.11022302e-16,
         3.33066907e-16],
       [-4.71844785e-16,  0.00000000e+00,  1.00000000e+00,
         4.44089210e-16],
       [ 6.66133815e-16,  8.88178420e-16,  3.88578059e-16,
         1.00000000e+00]])

# Exercise 8-4
- Derive the right-inverse for wide matrices

In [73]:
W = np.random.default_rng().random((3, 4))
W

array([[0.30232018, 0.01941763, 0.53447014, 0.41939713],
       [0.85807486, 0.05971023, 0.14295704, 0.5567182 ],
       [0.23311743, 0.57646983, 0.30165905, 0.73037922]])

In [87]:
R = W.T @ np.linalg.inv(W @ W.T)
R

array([[-0.28226874,  1.24569268, -0.45904869],
       [-0.97701727, -0.22414953,  1.25250603],
       [ 2.057042  , -0.774237  , -0.2950953 ],
       [ 0.01163424,  0.09909696,  0.64897586]])

In [88]:
W @ R

array([[ 1.00000000e+00, -1.84902617e-16, -2.32728076e-16],
       [-3.91012134e-16,  1.00000000e+00,  1.12857564e-16],
       [-7.53694884e-16,  2.03553090e-16,  1.00000000e+00]])

# Exercise 8-5
- Show that the psuedoinverse == Inverse for an invertable matrix
- Show that it's equal to the left inverse of a tall full rank matrix
- Show that it's equal to the right inverse of a wide full rank matrix

In [91]:
B = np.random.default_rng().random((3, 3))
B

array([[0.93627192, 0.69945686, 0.93974161],
       [0.86374621, 0.93328944, 0.76783612],
       [0.66212343, 0.39931364, 0.224396  ]])

In [92]:
np.linalg.pinv(B) - np.linalg.inv(B)

array([[-1.11022302e-15,  2.44249065e-15, -2.66453526e-15],
       [ 1.77635684e-15, -2.66453526e-15,  2.55351296e-15],
       [ 0.00000000e+00,  4.44089210e-16,  4.44089210e-16]])

In [95]:
# now tall
T = np.random.default_rng().random((4, 3))
T

array([[0.13190103, 0.36715505, 0.40489686],
       [0.93977207, 0.17413417, 0.05674645],
       [0.36823427, 0.32867613, 0.49403098],
       [0.76820138, 0.92714272, 0.78649937]])

In [98]:
L = np.linalg.inv(T.T @ T) @ T.T
L

array([[-0.21408913,  1.14134266,  0.57540345, -0.33356702],
       [-0.27205262, -0.60853438, -4.08080486,  2.74727419],
       [ 0.8562084 , -0.31390626,  4.14212426, -1.74850836]])

In [100]:
# again very small difference
np.linalg.pinv(T) - L

array([[-6.93889390e-16,  4.44089210e-16, -4.88498131e-15,
         1.16573418e-15],
       [ 1.83186799e-15,  1.33226763e-15,  1.68753900e-14,
        -7.54951657e-15],
       [-2.22044605e-16, -1.88737914e-15, -1.15463195e-14,
         5.99520433e-15]])

In [114]:
# now wide
W = np.random.default_rng().random((3, 4))
W

array([[0.0516683 , 0.0191358 , 0.10454075, 0.0913179 ],
       [0.97772788, 0.52649774, 0.0173897 , 0.58829074],
       [0.50273616, 0.91495244, 0.12133831, 0.89400271]])

In [115]:
R = W.T @ np.linalg.inv(W @ W.T)
R

array([[ 0.35407837,  1.46245706, -0.91480624],
       [-3.56208562, -0.42565899,  1.07407687],
       [ 7.97800706, -0.34834074, -0.2390545 ],
       [ 2.3636316 , -0.33949029,  0.56619894]])

In [116]:
np.linalg.pinv(W) - R

array([[ 4.82947016e-15, -2.22044605e-16,  0.00000000e+00],
       [ 3.10862447e-15,  1.11022302e-16, -8.88178420e-16],
       [-8.88178420e-16, -3.88578059e-16,  8.60422844e-16],
       [ 4.44089210e-16, -1.11022302e-16,  0.00000000e+00]])