In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Exercise 9-1
- A square $Q$ has the following equalities, demonstrate this in code by computing $Q$ from a random matrix and show for all 4 expressions the result is the identity matrix
$$
Q^T Q = Q Q^T = Q^{-1} Q = Q Q^{-1} = I
$$

In [3]:
A = np.random.default_rng().random((3, 3))
Q, _ = np.linalg.qr(A)
Q

array([[-0.53068632,  0.74381509,  0.40633871],
       [-0.57547509,  0.03575766, -0.81703721],
       [-0.62225433, -0.66742828,  0.40907095]])

In [4]:
Q.T @ Q

array([[ 1.00000000e+00,  1.27944418e-16,  3.61138357e-17],
       [ 1.27944418e-16,  1.00000000e+00, -8.78929436e-17],
       [ 3.61138357e-17, -8.78929436e-17,  1.00000000e+00]])

In [5]:
Q @ Q.T

array([[ 1.00000000e+00, -5.55111512e-17, -1.38777878e-16],
       [-5.55111512e-17,  1.00000000e+00,  0.00000000e+00],
       [-1.38777878e-16,  0.00000000e+00,  1.00000000e+00]])

In [6]:
np.linalg.inv(Q) @ Q

array([[ 1.00000000e+00,  5.40986613e-17, -5.47181626e-17],
       [ 3.34915837e-18,  1.00000000e+00,  1.30342068e-17],
       [ 4.96867925e-17,  9.72287832e-17,  1.00000000e+00]])

In [7]:
Q @ np.linalg.inv(Q)

array([[ 1.00000000e+00,  1.58759739e-17,  3.44371605e-17],
       [ 3.61889239e-17,  1.00000000e+00,  1.93829244e-16],
       [ 6.94546678e-17, -7.90241138e-18,  1.00000000e+00]])

# Exercise 9-3
- See what happens when you attempt QR decomposition to a matrix that is almost-but-not-quite orthogonal
- Create an orthogonal matrix $U$ from the QR decomposition of a 6x6 matrix
- Compute the QR decomposition of $U$ and confirm that $R = I$ and WHY
- Modify the norms of each column of $U$ to be 10-15 i.e. vector from 10-15 @ U
- Run modulated $U$ through QR decomposition and confirm that it's $R$ is the diagonal elements equaling 10-15
- What is the $Q^T Q$ for this matrix?
- Break the orthogonality of $U$ by setting element $u_{1,4} = 0$. What happens to $R$ and why?

In [10]:
U, _ = np.linalg.qr(np.random.default_rng().random((6, 6)))
U

array([[-0.07918398, -0.26091136,  0.73684914,  0.22533708, -0.4438026 ,
        -0.36738393],
       [-0.33723158, -0.80610302, -0.22420976,  0.26835078,  0.01877027,
         0.33739933],
       [-0.51346968, -0.07748051, -0.38034736, -0.32769338, -0.09345833,
        -0.6852475 ],
       [-0.3942302 ,  0.02559966,  0.4458975 , -0.05340132,  0.80047438,
        -0.03862239],
       [-0.54933743,  0.25226231,  0.18819836, -0.41333064, -0.38550398,
         0.52888369],
       [-0.39895436,  0.46024813, -0.16696111,  0.77209727, -0.06767505,
        -0.02041954]])

In [50]:
_, R = np.linalg.qr(U)
# R will be an identity matrix because U is already orthogonal and thus to QR decompose an already orthogonal matrix we would just need to split out the Identity matrix
R

array([[ 1.00000000e+00, -1.18431017e-17,  3.19098286e-17,
         5.77880624e-17, -1.02047154e-16, -1.05087994e-16],
       [ 0.00000000e+00,  1.00000000e+00, -2.23179611e-16,
        -8.40656281e-17,  4.06470427e-17,  9.80356307e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        -3.63128351e-17,  6.20062744e-17, -1.89868570e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  3.85545192e-16,  8.13811393e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00, -3.43284912e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [31]:
v = np.arange(10, 16)
v

array([10, 11, 12, 13, 14, 15])

In [32]:
np.linalg.norm(U[:,0])

np.float64(0.9999999999999999)

In [46]:
U_mod = v * U
U_mod

array([[ -0.79183983,  -2.87002498,   8.84218967,   2.92938204,
         -6.21323647,  -5.51075896],
       [ -3.37231576,  -8.8671332 ,  -2.69051717,   3.48856016,
          0.2627838 ,   5.06098988],
       [ -5.13469683,  -0.85228564,  -4.56416827,  -4.26001393,
         -1.30841664, -10.27871247],
       [ -3.94230195,   0.28159624,   5.35077004,  -0.69421718,
         11.20664135,  -0.5793359 ],
       [ -5.49337432,   2.77488537,   2.25838027,  -5.37329828,
         -5.39705567,   7.93325542],
       [ -3.98954365,   5.06272943,  -2.00353331,  10.03726448,
         -0.94745076,  -0.30629311]])

In [51]:
U_mod_Q, R_mod = np.linalg.qr(U_mod)
R_mod

array([[ 1.00000000e+01, -2.41296421e-16,  2.26476904e-15,
         8.24338339e-16, -2.72023499e-15, -1.46529761e-15],
       [ 0.00000000e+00,  1.10000000e+01, -4.14872507e-15,
         1.12911552e-15,  1.21625520e-15,  2.42221766e-15],
       [ 0.00000000e+00,  0.00000000e+00,  1.20000000e+01,
        -9.93273952e-16, -9.42907311e-17,  1.10821429e-15],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.30000000e+01,  5.99380663e-15,  1.16005627e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.40000000e+01, -4.37820625e-15],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.50000000e+01]])

In [52]:
U_mod_Q.T @ U_mod_Q

array([[ 1.00000000e+00,  7.17391635e-17, -1.73905471e-16,
         4.96379212e-17,  1.04754483e-16,  2.27054516e-16],
       [ 7.17391635e-17,  1.00000000e+00, -3.36766722e-17,
         1.09058190e-16,  6.26346426e-17,  3.07945417e-17],
       [-1.73905471e-16, -3.36766722e-17,  1.00000000e+00,
         8.96965099e-18, -3.71099244e-17, -1.30434521e-16],
       [ 4.96379212e-17,  1.09058190e-16,  8.96965099e-18,
         1.00000000e+00,  1.36059080e-16,  4.97584811e-18],
       [ 1.04754483e-16,  6.26346426e-17, -3.71099244e-17,
         1.36059080e-16,  1.00000000e+00,  7.49286923e-18],
       [ 2.27054516e-16,  3.07945417e-17, -1.30434521e-16,
         4.97584811e-18,  7.49286923e-18,  1.00000000e+00]])

In [53]:
U[0,3] = 0
_, Broken_R = np.linalg.qr(U)
# It is close to the identity matrix but not quite because by modifying U we made it linear dependent
Broken_R

array([[ 1.00000000e+00, -1.18431017e-17,  3.19098286e-17,
         1.78430875e-02, -1.02047154e-16, -1.05087994e-16],
       [ 0.00000000e+00,  1.00000000e+00, -2.23179611e-16,
         5.87930046e-02,  4.06470427e-17,  9.80356307e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        -1.66039434e-01,  6.20062744e-17, -1.89868570e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         9.58060078e-01,  1.04382998e-01,  8.64092181e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  9.94537174e-01, -9.06919668e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  9.96218448e-01]])